name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  schedule:
    - cron: '30 19 * * *'
jobs:
  tests:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install fish shell
        uses: fish-actions/install-fish@v1
      - name: Create syntactically valid fish shell function
        run: |
          cat << EOF >./valid-syntax.fish
          function valid-syntax
              echo "valid-syntax"
          end
          EOF
      - name: Syntax check valid fish file
        uses: ./
        with:
          pattern: valid-syntax.fish
